use serde::{Deserialize, Serialize};
use url::Url;

use crate::errors::{Error, ErrorKind};
use crate::utils::QueryParams;

/// Recognized query parameters in an authorization response.
const RECOGNIZED_PARAMS: &[&str] = &["code", "state", "iss"];

/// A successful Authorization Response as defined in [RFC 6749 §4.1.2].
///
/// Returned by the Authorization Server when the resource owner grants the
/// access request. The parameters are delivered as query components of the
/// Wallet's redirection URI.
///
/// [RFC 6749 §4.1.2]: https://www.rfc-editor.org/rfc/rfc6749.html#section-4.1.2
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AuthorizationResponse {
    /// The authorization code generated by the Authorization Server.
    ///
    /// REQUIRED. Short-lived, single-use, bound to the `client_id` and
    /// `redirect_uri` used in the Authorization Request.
    pub code: String,

    /// Opaque value used to maintain state between the request and callback.
    ///
    /// REQUIRED if the `state` parameter was present in the Authorization Request;
    /// the exact value received from the client is echoed back.
    pub state: Option<String>,

    /// The issuer identifier of the Authorization Server.
    ///
    /// OPTIONAL per [RFC 9207]. When present, contains the Authorization Server's
    /// issuer identifier URL.
    ///
    /// **Note:** This implementation enforces HAIP/FAPI2 mode, which requires
    /// `iss` to be present and validated. Base RFC 9207 permits responses without
    /// `iss` from ASes that do not support the parameter, but HAIP §4 mandates
    /// its presence for mix-up attack prevention.
    ///
    /// [RFC 9207]: https://www.rfc-editor.org/rfc/rfc9207.html
    pub iss: Option<String>,
}

impl AuthorizationResponse {
    /// Parses an [`AuthorizationResponse`] from the query string of a redirect URI.
    ///
    /// Accepts a raw query string such as `"code=abc&state=xyz"` (without the
    /// leading `?`). Percent-encoded values and `+`-as-space are decoded before
    /// parsing.
    ///
    /// # Errors
    ///
    /// Returns an error when:
    /// - The `code` parameter is absent or empty.
    /// - A recognized parameter (`code`, `state`, `iss`) appears more than once.
    pub fn from_query(query: &str) -> Result<Self, Error> {
        let params = QueryParams::parse(query, RECOGNIZED_PARAMS)?;

        let code = params.get("code").ok_or_else(|| {
            Error::message(
                ErrorKind::InvalidAuthorizationResponse,
                "authorization response is missing the required 'code' parameter",
            )
        })?;

        if code.trim().is_empty() {
            return Err(Error::message(
                ErrorKind::InvalidAuthorizationResponse,
                "authorization code must not be empty",
            ));
        }

        Ok(Self {
            code: code.to_owned(),
            state: params.get("state").map(ToOwned::to_owned),
            iss: params.get("iss").map(ToOwned::to_owned),
        })
    }

    /// Parses an [`AuthorizationResponse`] from a full redirect URI.
    ///
    /// Extracts and parses the query component from the URI. The URI must be
    /// a valid absolute URI (e.g. the value of the `Location` header in a 302
    /// redirect response).
    ///
    /// # Errors
    ///
    /// Returns an error when:
    /// - The URI cannot be parsed.
    /// - The URI contains no query string.
    /// - The `code` parameter is absent or empty.
    /// - A recognized parameter appears more than once.
    pub fn from_redirect_uri(redirect_uri: &str) -> Result<Self, Error> {
        let parsed = Url::parse(redirect_uri).map_err(|_| {
            Error::message(
                ErrorKind::InvalidAuthorizationResponse,
                format!("'{redirect_uri}' is not a valid URI"),
            )
        })?;

        let query = parsed.query().ok_or_else(|| {
            Error::message(
                ErrorKind::InvalidAuthorizationResponse,
                "redirect URI has no query string",
            )
        })?;

        Self::from_query(query)
    }

    /// Validates that the required `code` field is non-empty.
    ///
    /// # Errors
    ///
    /// Returns [`ErrorKind::InvalidAuthorizationResponse`] if `code` is blank.
    pub fn validate(&self) -> Result<(), Error> {
        if self.code.trim().is_empty() {
            return Err(Error::message(
                ErrorKind::InvalidAuthorizationResponse,
                "authorization code must not be empty",
            ));
        }
        Ok(())
    }

    /// Validates that the `iss` parameter matches the expected Authorization Server issuer.
    ///
    /// Per [RFC 9207] and [HAIP §4], the Wallet MUST verify that the `iss` parameter
    /// in the authorization response matches the issuer identifier of the Authorization Server
    /// that the Wallet expected to receive the response from.
    ///
    /// **Note:** This implementation enforces strict mode, rejecting responses without `iss`.
    /// Base RFC 9207 permits optional `iss`, but FAPI2/HAIP requires it for security.
    ///
    /// # Arguments
    ///
    /// * `expected_issuer` - The expected Authorization Server issuer URL (from AS metadata).
    ///
    /// # String Comparison
    ///
    /// Per RFC 9207 §2.4, comparison uses simple string equality after form-decoding.
    /// If `expected_issuer` comes from a parsed `Url`, the `url` crate's normalization
    /// (e.g., trailing slash on bare origins) is applied. Pass the raw metadata value
    /// if exact string matching is required.
    ///
    /// # Errors
    ///
    /// Returns [`ErrorKind::InvalidAuthorizationResponse`] when:
    /// - `iss` is missing (strict mode enforced per FAPI2/HAIP)
    /// - `iss` does not match the expected issuer
    ///
    /// [RFC 9207]: https://www.rfc-editor.org/rfc/rfc9207.html
    /// [HAIP §4]: https://openid.net/specs/openid4vc-high-assurance-interoperability-profile-1_0.html#section-4
    pub fn validate_iss(&self, expected_issuer: &str) -> Result<(), Error> {
        let iss = self.iss.as_deref().ok_or_else(|| {
            Error::message(
                ErrorKind::InvalidAuthorizationResponse,
                "authorization response is missing the required 'iss' parameter (per RFC 9207 / HAIP)",
            )
        })?;

        if iss != expected_issuer {
            return Err(Error::message(
                ErrorKind::InvalidAuthorizationResponse,
                format!(
                    "authorization response 'iss' mismatch: expected '{}', got '{}'",
                    expected_issuer, iss
                ),
            ));
        }

        Ok(())
    }
}

/// An OAuth 2.0 Pushed Authorization Response (PAR) as outlined in [OID4VCI §5.1.4].
///
/// [OID4VCI §5.1.4]: https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#section-5.1.4
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PushedAuthorizationResponse {
    /// The request URI returned by the authorization server.
    pub request_uri: String,
    /// The lifetime in seconds of the request URI.
    pub expires_in: u64,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn authorization_response_validates_non_empty_code() {
        let valid = AuthorizationResponse {
            code: "abc123".to_string(),
            state: None,
            iss: None,
        };
        assert!(valid.validate().is_ok());
    }

    #[test]
    fn authorization_response_rejects_empty_code() {
        let invalid = AuthorizationResponse {
            code: "   ".to_string(),
            state: None,
            iss: None,
        };
        let err = invalid.validate().unwrap_err();
        assert_eq!(err.kind(), ErrorKind::InvalidAuthorizationResponse);
        assert!(err.to_string().contains("empty"));
    }

    #[test]
    fn from_query_parses_response_with_state() {
        let response =
            AuthorizationResponse::from_query("code=SplxlOBeZQQYbYS6WxSbIA&state=xyz").unwrap();

        assert_eq!(response.code, "SplxlOBeZQQYbYS6WxSbIA");
        assert_eq!(response.state.as_deref(), Some("xyz"));
    }

    #[test]
    fn from_query_parses_response_without_state() {
        let response = AuthorizationResponse::from_query("code=abc123").unwrap();

        assert_eq!(response.code, "abc123");
        assert!(response.state.is_none());
    }

    #[test]
    fn from_query_rejects_missing_code() {
        let err = AuthorizationResponse::from_query("state=xyz").unwrap_err();
        assert_eq!(err.kind(), ErrorKind::InvalidAuthorizationResponse);
        assert!(err.to_string().contains("'code'"));
    }

    #[test]
    fn from_query_rejects_empty_code() {
        let err = AuthorizationResponse::from_query("code=").unwrap_err();
        assert_eq!(err.kind(), ErrorKind::InvalidAuthorizationResponse);
        assert!(err.to_string().contains("empty"));
    }

    #[test]
    fn from_query_rejects_blank_code() {
        let err = AuthorizationResponse::from_query("code=%20%20").unwrap_err();
        assert_eq!(err.kind(), ErrorKind::InvalidAuthorizationResponse);
        assert!(err.to_string().contains("empty"));
    }

    #[test]
    fn from_query_handles_percent_encoded_state() {
        let response =
            AuthorizationResponse::from_query("code=abc&state=state%3Dvalue%26other%3Ddata")
                .unwrap();

        assert_eq!(response.state.as_deref(), Some("state=value&other=data"));
    }

    #[test]
    fn from_query_handles_plus_as_space_in_state() {
        let response = AuthorizationResponse::from_query("code=abc&state=hello+world").unwrap();

        assert_eq!(response.state.as_deref(), Some("hello world"));
    }

    #[test]
    fn from_query_ignores_unrecognized_parameters() {
        // Per RFC 6749 §4.1.2 the client MUST ignore unrecognized response parameters.
        let response =
            AuthorizationResponse::from_query("code=abc&state=s&unknown_param=value").unwrap();

        assert_eq!(response.code, "abc");
        assert_eq!(response.state.as_deref(), Some("s"));
    }

    #[test]
    fn from_query_rejects_duplicate_code_parameter() {
        let err = AuthorizationResponse::from_query("code=first&code=second").unwrap_err();
        assert_eq!(err.kind(), ErrorKind::InvalidAuthorizationResponse);
        assert!(err.to_string().contains("duplicate 'code'"));
    }

    #[test]
    fn from_query_rejects_duplicate_state_parameter() {
        let err =
            AuthorizationResponse::from_query("code=abc&state=first&state=second").unwrap_err();
        assert_eq!(err.kind(), ErrorKind::InvalidAuthorizationResponse);
        assert!(err.to_string().contains("duplicate 'state'"));
    }

    #[test]
    fn from_redirect_uri_parses_successful_redirect() {
        let uri = "https://wallet.example.org/cb?code=SplxlOBeZQQYbYS6WxSbIA&state=xyz";
        let response = AuthorizationResponse::from_redirect_uri(uri).unwrap();

        assert_eq!(response.code, "SplxlOBeZQQYbYS6WxSbIA");
        assert_eq!(response.state.as_deref(), Some("xyz"));
    }

    #[test]
    fn from_redirect_uri_rejects_invalid_uri() {
        let err = AuthorizationResponse::from_redirect_uri("not a uri").unwrap_err();
        assert_eq!(err.kind(), ErrorKind::InvalidAuthorizationResponse);
    }

    #[test]
    fn from_redirect_uri_rejects_uri_without_query() {
        let err =
            AuthorizationResponse::from_redirect_uri("https://wallet.example.org/cb").unwrap_err();
        assert_eq!(err.kind(), ErrorKind::InvalidAuthorizationResponse);
        assert!(err.to_string().contains("no query string"));
    }

    #[test]
    fn from_redirect_uri_rejects_missing_code() {
        let err =
            AuthorizationResponse::from_redirect_uri("https://wallet.example.org/cb?state=xyz")
                .unwrap_err();
        assert_eq!(err.kind(), ErrorKind::InvalidAuthorizationResponse);
    }

    #[test]
    fn from_redirect_uri_rejects_duplicate_code() {
        let err =
            AuthorizationResponse::from_redirect_uri("https://wallet.example.org/cb?code=a&code=b")
                .unwrap_err();
        assert_eq!(err.kind(), ErrorKind::InvalidAuthorizationResponse);
        assert!(err.to_string().contains("duplicate 'code'"));
    }

    /// From OpenID4VCI §5.2 — Successful Authorization Response.
    #[test]
    fn spec_successful_authorization_response_example() {
        // Location: https://wallet.example.org/cb?code=SplxlOBeZQQYbYS6WxSbIA
        let uri = "https://wallet.example.org/cb?code=SplxlOBeZQQYbYS6WxSbIA";
        let response = AuthorizationResponse::from_redirect_uri(uri).unwrap();

        assert_eq!(response.code, "SplxlOBeZQQYbYS6WxSbIA");
        assert!(response.state.is_none());
    }

    /// From RFC 6749 §4.1.2 — successful response example.
    #[test]
    fn rfc6749_successful_response_example() {
        // HTTP/1.1 302 Found
        // Location: https://client.example.com/cb?code=SplxlOBeZQQYbYS6WxSbIA&state=xyz
        let uri = "https://client.example.com/cb?code=SplxlOBeZQQYbYS6WxSbIA&state=xyz";
        let response = AuthorizationResponse::from_redirect_uri(uri).unwrap();

        assert_eq!(response.code, "SplxlOBeZQQYbYS6WxSbIA");
        assert_eq!(response.state.as_deref(), Some("xyz"));
    }

    // RFC 9207 iss parameter tests

    #[test]
    fn from_query_parses_iss_parameter() {
        let response =
            AuthorizationResponse::from_query("code=abc123&state=xyz&iss=https://as.example.com")
                .unwrap();

        assert_eq!(response.code, "abc123");
        assert_eq!(response.state.as_deref(), Some("xyz"));
        assert_eq!(response.iss.as_deref(), Some("https://as.example.com"));
    }

    #[test]
    fn from_query_parses_iss_without_state() {
        let response =
            AuthorizationResponse::from_query("code=abc123&iss=https://as.example.com").unwrap();

        assert_eq!(response.code, "abc123");
        assert!(response.state.is_none());
        assert_eq!(response.iss.as_deref(), Some("https://as.example.com"));
    }

    #[test]
    fn from_query_handles_url_encoded_iss() {
        let response =
            AuthorizationResponse::from_query("code=abc&iss=https%3A%2F%2Fas.example.com%3A8443")
                .unwrap();

        assert_eq!(response.iss.as_deref(), Some("https://as.example.com:8443"));
    }

    #[test]
    fn validate_iss_accepts_matching_issuer() {
        let response = AuthorizationResponse {
            code: "abc123".to_string(),
            state: None,
            iss: Some("https://as.example.com".to_string()),
        };

        assert!(response.validate_iss("https://as.example.com").is_ok());
    }

    #[test]
    fn validate_iss_rejects_mismatched_issuer() {
        let response = AuthorizationResponse {
            code: "abc123".to_string(),
            state: None,
            iss: Some("https://attacker.example.com".to_string()),
        };

        let err = response.validate_iss("https://as.example.com").unwrap_err();
        assert_eq!(err.kind(), ErrorKind::InvalidAuthorizationResponse);
        assert!(err.to_string().contains("iss' mismatch"));
        assert!(err.to_string().contains("https://as.example.com"));
        assert!(err.to_string().contains("https://attacker.example.com"));
    }

    #[test]
    fn validate_iss_rejects_missing_issuer() {
        let response = AuthorizationResponse {
            code: "abc123".to_string(),
            state: None,
            iss: None,
        };

        let err = response.validate_iss("https://as.example.com").unwrap_err();
        assert_eq!(err.kind(), ErrorKind::InvalidAuthorizationResponse);
        assert!(
            err.to_string()
                .contains("missing the required 'iss' parameter")
        );
        assert!(err.to_string().contains("RFC 9207"));
        assert!(err.to_string().contains("HAIP"));
    }

    /// From RFC 9207 — Authorization Response with iss identifier.
    #[test]
    fn rfc9207_authorization_response_with_iss() {
        // Per RFC 9207, the AS includes 'iss' in the authorization response
        let uri = "https://wallet.example.org/cb?code=SplxlOBeZQQYbYS6WxSbIA&state=xyz&iss=https://as.example.com";
        let response = AuthorizationResponse::from_redirect_uri(uri).unwrap();

        assert_eq!(response.code, "SplxlOBeZQQYbYS6WxSbIA");
        assert_eq!(response.state.as_deref(), Some("xyz"));
        assert_eq!(response.iss.as_deref(), Some("https://as.example.com"));

        // Validation succeeds when iss matches expected AS issuer
        assert!(response.validate_iss("https://as.example.com").is_ok());
    }

    #[test]
    fn from_query_rejects_duplicate_iss_parameter() {
        let err = AuthorizationResponse::from_query("code=abc&iss=https://a.com&iss=https://b.com")
            .unwrap_err();
        assert_eq!(err.kind(), ErrorKind::InvalidAuthorizationResponse);
        assert!(err.to_string().contains("duplicate 'iss'"));
    }
}
