[default]
extend-ignore-identifiers-re = []

[default.extend-identifiers]

[default.extend-words]

[files]
extend-exclude = [
  "cloud-wallet-crypto/src/jwk.rs",
  "cloud-wallet-crypto/src/jwk/tests.rs",
  "cloud-wallet-openid4vc/tests_metadata/issuer_metadata.json"
]
