use serde::{Deserialize, Serialize};
use url::Url;

use crate::errors::{Error, ErrorKind};
use crate::issuance::query_params::QueryParams;

/// Recognized query parameters in an authorization response.
const RECOGNIZED_PARAMS: &[&str] = &["code", "state"];

/// A successful Authorization Response as defined in [RFC 6749 §4.1.2].
///
/// Returned by the Authorization Server when the resource owner grants the
/// access request. The parameters are delivered as query components of the
/// Wallet's redirection URI.
///
/// [RFC 6749 §4.1.2]: https://www.rfc-editor.org/rfc/rfc6749.html#section-4.1.2
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AuthorizationCode {
    /// The authorization code generated by the Authorization Server.
    ///
    /// REQUIRED. Short-lived, single-use, bound to the `client_id` and
    /// `redirect_uri` used in the Authorization Request.
    pub code: String,

    /// Opaque value used to maintain state between the request and callback.
    ///
    /// REQUIRED if the `state` parameter was present in the Authorization Request;
    /// the exact value received from the client is echoed back.
    pub state: Option<String>,
}

impl AuthorizationCode {
    /// Validates that the required `code` field is non-empty.
    ///
    /// # Errors
    ///
    /// Returns [`ErrorKind::InvalidCredentialOffer`] if `code` is blank.
    pub fn validate(&self) -> Result<(), Error> {
        if self.code.trim().is_empty() {
            return Err(Error::message(
                ErrorKind::InvalidCredentialOffer,
                "authorization code must not be empty",
            ));
        }
        Ok(())
    }
}

/// A parsed Authorization Response from the Authorization Code Flow.
///
/// Per [OpenID4VCI §5.2] and [RFC 6749 §4.1.2], after the End-User grants
/// consent the Authorization Server redirects the user-agent back to the
/// Wallet's `redirect_uri` with a `code` parameter in the query string.
///
/// [OpenID4VCI §5.2]: https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#name-successful-authorization-re
/// [RFC 6749 §4.1.2]: https://www.rfc-editor.org/rfc/rfc6749.html#section-4.1.2
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AuthorizationResponse {
    /// The authorization code returned by the Authorization Server, ready to
    /// be exchanged for an access token at the Token Endpoint.
    pub code: AuthorizationCode,
}

impl AuthorizationResponse {
    /// Parses an [`AuthorizationResponse`] from the query string of a redirect URI.
    ///
    /// Accepts a raw query string such as `"code=abc&state=xyz"` (without the
    /// leading `?`). Percent-encoded values and `+`-as-space are decoded before
    /// parsing.
    ///
    /// # Errors
    ///
    /// Returns an error when:
    /// - The `code` parameter is absent or empty.
    /// - A recognized parameter (`code`, `state`) appears more than once.
    pub fn from_query(query: &str) -> Result<Self, Error> {
        let params = QueryParams::parse(query, RECOGNIZED_PARAMS)?;

        let code = params.get("code").ok_or_else(|| {
            Error::message(
                ErrorKind::InvalidCredentialOffer,
                "authorization response is missing the required 'code' parameter",
            )
        })?;

        if code.trim().is_empty() {
            return Err(Error::message(
                ErrorKind::InvalidCredentialOffer,
                "authorization code must not be empty",
            ));
        }

        Ok(Self {
            code: AuthorizationCode {
                code: code.to_owned(),
                state: params.get("state").map(ToOwned::to_owned),
            },
        })
    }

    /// Parses an [`AuthorizationResponse`] from a full redirect URI.
    ///
    /// Extracts and parses the query component from the URI. The URI must be
    /// a valid absolute URI (e.g. the value of the `Location` header in a 302
    /// redirect response).
    ///
    /// # Errors
    ///
    /// Returns an error when:
    /// - The URI cannot be parsed.
    /// - The URI contains no query string.
    /// - The `code` parameter is absent or empty.
    /// - A recognized parameter appears more than once.
    pub fn from_redirect_uri(redirect_uri: &str) -> Result<Self, Error> {
        let parsed = Url::parse(redirect_uri).map_err(|_| {
            Error::message(
                ErrorKind::InvalidCredentialOffer,
                format!("'{redirect_uri}' is not a valid URI"),
            )
        })?;

        let query = parsed.query().ok_or_else(|| {
            Error::message(
                ErrorKind::InvalidCredentialOffer,
                "redirect URI has no query string",
            )
        })?;

        Self::from_query(query)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn authorization_code_validates_non_empty_code() {
        let valid = AuthorizationCode {
            code: "abc123".to_string(),
            state: None,
        };
        assert!(valid.validate().is_ok());
    }

    #[test]
    fn authorization_code_rejects_empty_code() {
        let invalid = AuthorizationCode {
            code: "   ".to_string(),
            state: None,
        };
        let err = invalid.validate().unwrap_err();
        assert_eq!(err.kind(), ErrorKind::InvalidCredentialOffer);
        assert!(err.to_string().contains("empty"));
    }

    #[test]
    fn from_query_parses_response_with_state() {
        let response =
            AuthorizationResponse::from_query("code=SplxlOBeZQQYbYS6WxSbIA&state=xyz").unwrap();

        assert_eq!(response.code.code, "SplxlOBeZQQYbYS6WxSbIA");
        assert_eq!(response.code.state.as_deref(), Some("xyz"));
    }

    #[test]
    fn from_query_parses_response_without_state() {
        let response = AuthorizationResponse::from_query("code=abc123").unwrap();

        assert_eq!(response.code.code, "abc123");
        assert!(response.code.state.is_none());
    }

    #[test]
    fn from_query_rejects_missing_code() {
        let err = AuthorizationResponse::from_query("state=xyz").unwrap_err();
        assert_eq!(err.kind(), ErrorKind::InvalidCredentialOffer);
        assert!(err.to_string().contains("'code'"));
    }

    #[test]
    fn from_query_rejects_empty_code() {
        let err = AuthorizationResponse::from_query("code=").unwrap_err();
        assert_eq!(err.kind(), ErrorKind::InvalidCredentialOffer);
        assert!(err.to_string().contains("empty"));
    }

    #[test]
    fn from_query_rejects_blank_code() {
        let err = AuthorizationResponse::from_query("code=%20%20").unwrap_err();
        assert_eq!(err.kind(), ErrorKind::InvalidCredentialOffer);
        assert!(err.to_string().contains("empty"));
    }

    #[test]
    fn from_query_handles_percent_encoded_state() {
        let response =
            AuthorizationResponse::from_query("code=abc&state=state%3Dvalue%26other%3Ddata")
                .unwrap();

        assert_eq!(
            response.code.state.as_deref(),
            Some("state=value&other=data")
        );
    }

    #[test]
    fn from_query_handles_plus_as_space_in_state() {
        let response = AuthorizationResponse::from_query("code=abc&state=hello+world").unwrap();

        assert_eq!(response.code.state.as_deref(), Some("hello world"));
    }

    #[test]
    fn from_query_ignores_unrecognized_parameters() {
        // Per RFC 6749 §4.1.2 the client MUST ignore unrecognized response parameters.
        let response =
            AuthorizationResponse::from_query("code=abc&state=s&unknown_param=value").unwrap();

        assert_eq!(response.code.code, "abc");
        assert_eq!(response.code.state.as_deref(), Some("s"));
    }

    #[test]
    fn from_query_rejects_duplicate_code_parameter() {
        let err = AuthorizationResponse::from_query("code=first&code=second").unwrap_err();
        assert_eq!(err.kind(), ErrorKind::InvalidCredentialOffer);
        assert!(err.to_string().contains("duplicate 'code'"));
    }

    #[test]
    fn from_query_rejects_duplicate_state_parameter() {
        let err =
            AuthorizationResponse::from_query("code=abc&state=first&state=second").unwrap_err();
        assert_eq!(err.kind(), ErrorKind::InvalidCredentialOffer);
        assert!(err.to_string().contains("duplicate 'state'"));
    }

    // ── AuthorizationResponse::from_redirect_uri ──────────────────────────

    #[test]
    fn from_redirect_uri_parses_successful_redirect() {
        let uri = "https://wallet.example.org/cb?code=SplxlOBeZQQYbYS6WxSbIA&state=xyz";
        let response = AuthorizationResponse::from_redirect_uri(uri).unwrap();

        assert_eq!(response.code.code, "SplxlOBeZQQYbYS6WxSbIA");
        assert_eq!(response.code.state.as_deref(), Some("xyz"));
    }

    #[test]
    fn from_redirect_uri_rejects_invalid_uri() {
        let err = AuthorizationResponse::from_redirect_uri("not a uri").unwrap_err();
        assert_eq!(err.kind(), ErrorKind::InvalidCredentialOffer);
    }

    #[test]
    fn from_redirect_uri_rejects_uri_without_query() {
        let err =
            AuthorizationResponse::from_redirect_uri("https://wallet.example.org/cb").unwrap_err();
        assert_eq!(err.kind(), ErrorKind::InvalidCredentialOffer);
        assert!(err.to_string().contains("no query string"));
    }

    #[test]
    fn from_redirect_uri_rejects_missing_code() {
        let err =
            AuthorizationResponse::from_redirect_uri("https://wallet.example.org/cb?state=xyz")
                .unwrap_err();
        assert_eq!(err.kind(), ErrorKind::InvalidCredentialOffer);
    }

    #[test]
    fn from_redirect_uri_rejects_duplicate_code() {
        let err =
            AuthorizationResponse::from_redirect_uri("https://wallet.example.org/cb?code=a&code=b")
                .unwrap_err();
        assert_eq!(err.kind(), ErrorKind::InvalidCredentialOffer);
        assert!(err.to_string().contains("duplicate 'code'"));
    }

    // ── Spec non-normative examples ───────────────────────────────────────

    /// From OpenID4VCI §5.2 — Successful Authorization Response.
    #[test]
    fn spec_successful_authorization_response_example() {
        // Location: https://wallet.example.org/cb?code=SplxlOBeZQQYbYS6WxSbIA
        let uri = "https://wallet.example.org/cb?code=SplxlOBeZQQYbYS6WxSbIA";
        let response = AuthorizationResponse::from_redirect_uri(uri).unwrap();

        assert_eq!(response.code.code, "SplxlOBeZQQYbYS6WxSbIA");
        assert!(response.code.state.is_none());
    }

    /// From RFC 6749 §4.1.2 — successful response example.
    #[test]
    fn rfc6749_successful_response_example() {
        // HTTP/1.1 302 Found
        // Location: https://client.example.com/cb?code=SplxlOBeZQQYbYS6WxSbIA&state=xyz
        let uri = "https://client.example.com/cb?code=SplxlOBeZQQYbYS6WxSbIA&state=xyz";
        let response = AuthorizationResponse::from_redirect_uri(uri).unwrap();

        assert_eq!(response.code.code, "SplxlOBeZQQYbYS6WxSbIA");
        assert_eq!(response.code.state.as_deref(), Some("xyz"));
    }
}
