use std::collections::HashMap;

use percent_encoding::percent_decode_str;
use serde::{Deserialize, Serialize};
use url::Url;

use crate::errors::{Error, ErrorKind};

// ── Successful Authorization Response ────────────────────────────────────────

/// A successful Authorization Response as defined in [RFC 6749 §4.1.2].
///
/// Returned by the Authorization Server when the resource owner grants the
/// access request. The parameters are delivered as query components of the
/// Wallet's redirection URI.
///
/// [RFC 6749 §4.1.2]: https://www.rfc-editor.org/rfc/rfc6749.html#section-4.1.2

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AuthorizationCode {
    /// The authorization code generated by the Authorization Server.
    ///
    /// REQUIRED. Short-lived, single-use, bound to the `client_id` and
    /// `redirect_uri` used in the Authorization Request.
    pub code: String,

    /// Opaque value used to maintain state between the request and callback.
    ///
    /// REQUIRED if the `state` parameter was present in the Authorization Request;
    /// the exact value received from the client is echoed back.
    pub state: Option<String>,
}

impl AuthorizationCode {
    /// Validates that the required `code` field is non-empty.
    ///
    /// # Errors
    ///
    /// Returns [`ErrorKind::InvalidCredentialOffer`] if `code` is blank.
    pub fn validate(&self) -> Result<(), Error> {
        if self.code.trim().is_empty() {
            return Err(Error::message(
                ErrorKind::InvalidCredentialOffer,
                "authorization code must not be empty",
            ));
        }
        Ok(())
    }
}

// ── Authorization Response ─────────────────────────────────────────────────────

/// A successful Authorization Response from the Authorization Code Flow.
///
/// Per [OpenID4VCI §5.2], the Authorization Server redirects the user-agent
/// back to the Wallet's `redirect_uri` with a `code` parameter.
///
/// [OpenID4VCI §5.2]: https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#name-successful-authorization-re
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AuthorizationResponse {
    /// The authorization code ready to be exchanged at the Token Endpoint.
    pub code: AuthorizationCode,
}

impl AuthorizationResponse {
    /// Parses an [`AuthorizationResponse`] from the query string of a redirect URI.
    ///
    /// Accepts a raw query string such as `"code=abc&state=xyz"` (without the
    /// leading `?`). Percent-encoded values are decoded before parsing.
    ///
    /// # Errors
    ///
    /// Returns an error when:
    /// - A `code` parameter is not present.
    /// - A `code` parameter is present but empty.
    pub fn from_query(query: &str) -> Result<Self, Error> {
        let params = parse_query_params(query);
        Self::from_params(&params)
    }

    /// Parses an [`AuthorizationResponse`] from a full redirect URI.
    ///
    /// Extracts and parses the query component from the URI. The URI must be
    /// a valid absolute URI (e.g. the value of the `Location` header in a 302
    /// redirect response).
    ///
    /// # Errors
    ///
    /// Returns an error when:
    /// - The URI cannot be parsed.
    /// - The URI contains no query string.
    /// - A `code` parameter is not present in the query.
    pub fn from_redirect_uri(redirect_uri: &str) -> Result<Self, Error> {
        let parsed = Url::parse(redirect_uri).map_err(|_| {
            Error::message(
                ErrorKind::InvalidCredentialOffer,
                format!("'{}' is not a valid URI", redirect_uri),
            )
        })?;

        let query = parsed.query().ok_or_else(|| {
            Error::message(
                ErrorKind::InvalidCredentialOffer,
                "redirect URI has no query string",
            )
        })?;

        Self::from_query(query)
    }

    /// Returns the authorization code.
    pub fn code(&self) -> &AuthorizationCode {
        &self.code
    }

    /// Returns the `state` value echoed in this response, if any.
    pub fn state(&self) -> Option<&str> {
        self.code.state.as_deref()
    }

    // ── Internal helpers ──────────────────────────────────────────────────

    fn from_params(params: &HashMap<String, String>) -> Result<Self, Error> {
        // A `code` parameter indicates a successful response.
        if let Some(code) = params.get("code") {
            if code.trim().is_empty() {
                return Err(Error::message(
                    ErrorKind::InvalidCredentialOffer,
                    "authorization code must not be empty",
                ));
            }
            return Ok(Self {
                code: AuthorizationCode {
                    code: code.clone(),
                    state: params.get("state").cloned(),
                },
            });
        }

        Err(Error::message(
            ErrorKind::InvalidCredentialOffer,
            "authorization response must contain a 'code' parameter",
        ))
    }
}

// ── Query parsing helpers ─────────────────────────────────────────────────────

/// Parses a `application/x-www-form-urlencoded` query string into a map.
///
/// Handles percent-encoding and `+`-as-space decoding for each key and value.
fn parse_query_params(query: &str) -> HashMap<String, String> {
    query
        .split('&')
        .filter_map(|pair| {
            let mut parts = pair.splitn(2, '=');
            let key = parts.next()?.trim();
            let value = parts.next().unwrap_or("");

            if key.is_empty() {
                return None;
            }

            // Decode `+` as space, then percent-decode.
            let key_decoded = decode_form_value(key);
            let value_decoded = decode_form_value(value);

            Some((key_decoded, value_decoded))
        })
        .collect()
}

/// Decodes a single `application/x-www-form-urlencoded` value.
///
/// Replaces `+` with a space, then applies percent-decoding.
fn decode_form_value(s: &str) -> String {
    let plus_decoded = s.replace('+', " ");
    percent_decode_str(&plus_decoded)
        .decode_utf8_lossy()
        .into_owned()
}

#[cfg(test)]
mod tests {
    use super::*;

    // ── AuthorizationCode ─────────────────────────────────────────────────

    #[test]
    fn authorization_code_validates_non_empty_code() {
        let valid = AuthorizationCode {
            code: "abc123".to_string(),
            state: None,
        };
        assert!(valid.validate().is_ok());
    }

    #[test]
    fn authorization_code_rejects_empty_code() {
        let invalid = AuthorizationCode {
            code: "   ".to_string(),
            state: None,
        };
        let err = invalid.validate().unwrap_err();
        assert_eq!(err.kind(), ErrorKind::InvalidCredentialOffer);
        assert!(err.to_string().contains("empty"));
    }

    // ── AuthorizationResponse::from_query ─────────────────────────────────

    #[test]
    fn from_query_parses_successful_response_with_state() {
        let query = "code=SplxlOBeZQQYbYS6WxSbIA&state=xyz";
        let response = AuthorizationResponse::from_query(query).unwrap();

        assert_eq!(response.code.code, "SplxlOBeZQQYbYS6WxSbIA");
        assert_eq!(response.code.state.as_deref(), Some("xyz"));
    }

    #[test]
    fn from_query_parses_successful_response_without_state() {
        let query = "code=abc123";
        let response = AuthorizationResponse::from_query(query).unwrap();

        assert_eq!(response.code.code, "abc123");
        assert!(response.code.state.is_none());
    }

    #[test]
    fn from_query_rejects_empty_code() {
        let query = "code=";
        let err = AuthorizationResponse::from_query(query).unwrap_err();
        assert_eq!(err.kind(), ErrorKind::InvalidCredentialOffer);
        assert!(err.to_string().contains("empty"));
    }

    #[test]
    fn from_query_rejects_missing_code() {
        let query = "state=xyz&other=value";
        let err = AuthorizationResponse::from_query(query).unwrap_err();
        assert_eq!(err.kind(), ErrorKind::InvalidCredentialOffer);
        assert!(err.to_string().contains("code"));
    }

    #[test]
    fn from_query_handles_percent_encoded_values() {
        // Percent-encoded state
        let query = "code=abc123&state=state%3Dvalue%26other%3Ddata";
        let response = AuthorizationResponse::from_query(query).unwrap();

        assert_eq!(response.code.code, "abc123");
        assert_eq!(
            response.code.state.as_deref(),
            Some("state=value&other=data")
        );
    }

    // ── AuthorizationResponse::from_redirect_uri ──────────────────────────

    #[test]
    fn from_redirect_uri_parses_successful_redirect() {
        let uri = "https://wallet.example.org/cb?code=SplxlOBeZQQYbYS6WxSbIA&state=xyz";
        let response = AuthorizationResponse::from_redirect_uri(uri).unwrap();

        assert_eq!(response.code.code, "SplxlOBeZQQYbYS6WxSbIA");
        assert_eq!(response.code.state.as_deref(), Some("xyz"));
    }

    #[test]
    fn from_redirect_uri_rejects_invalid_uri() {
        let err = AuthorizationResponse::from_redirect_uri("not a uri").unwrap_err();
        assert_eq!(err.kind(), ErrorKind::InvalidCredentialOffer);
    }

    #[test]
    fn from_redirect_uri_rejects_uri_without_query() {
        let err =
            AuthorizationResponse::from_redirect_uri("https://wallet.example.org/cb").unwrap_err();
        assert_eq!(err.kind(), ErrorKind::InvalidCredentialOffer);
        assert!(err.to_string().contains("no query string"));
    }

    // ── AuthorizationResponse helper methods ──────────────────────────────

    #[test]
    fn code_accessor_returns_authorization_code() {
        let response = AuthorizationResponse::from_query("code=abc123").unwrap();
        assert_eq!(response.code().code, "abc123");
    }

    #[test]
    fn state_accessor_works() {
        let with_state = AuthorizationResponse::from_query("code=abc&state=state1").unwrap();
        assert_eq!(with_state.state(), Some("state1"));

        let no_state = AuthorizationResponse::from_query("code=abc").unwrap();
        assert!(no_state.state().is_none());
    }

    // ── Spec non-normative examples ───────────────────────────────────────

    /// From OpenID4VCI §5.2 — Successful Authorization Response.
    #[test]
    fn spec_successful_authorization_response_example() {
        // Location: https://wallet.example.org/cb?code=SplxlOBeZQQYbYS6WxSbIA
        let uri = "https://wallet.example.org/cb?code=SplxlOBeZQQYbYS6WxSbIA";
        let response = AuthorizationResponse::from_redirect_uri(uri).unwrap();

        assert_eq!(response.code.code, "SplxlOBeZQQYbYS6WxSbIA");
        assert!(response.code.state.is_none());
    }

    /// From RFC 6749 §4.1.2 — successful response example.
    #[test]
    fn rfc6749_successful_response_example() {
        // HTTP/1.1 302 Found
        // Location: https://client.example.com/cb?code=SplxlOBeZQQYbYS6WxSbIA&state=xyz
        let uri = "https://client.example.com/cb?code=SplxlOBeZQQYbYS6WxSbIA&state=xyz";
        let response = AuthorizationResponse::from_redirect_uri(uri).unwrap();

        assert_eq!(response.code.code, "SplxlOBeZQQYbYS6WxSbIA");
        assert_eq!(response.code.state.as_deref(), Some("xyz"));
    }
}
