use std::collections::HashMap;
use std::fmt;
use std::sync::Arc;
use std::time::Duration;

use aws_config::SdkConfig;
use aws_sdk_kms::primitives::Blob;
use aws_sdk_kms::types::DataKeySpec;
use aws_sdk_kms::{Client as KmsClient, error::SdkError};
use cloud_wallet_crypto::aead::{Key as AesKey, NONCE_LENGTH, TAG_LENGTH};
use cloud_wallet_crypto::{self as crypto, secret::Secret};
use color_eyre::eyre::eyre;
use dashmap::DashMap;
use tokio::sync::OnceCell;

use crate::cache::Cache;
use crate::key::{
    dek::{DataEncryptionKey, Id as DekId},
    master::Id as MasterId,
};
use crate::nonce::NonceGenerator;
use crate::provider::Provider;
use crate::storage::Storage;
use crate::{AeadAlgorithm, Error, Result};

const MAX_CACHE_CAPACITY: u64 = 100;
const CACHE_TTL: Duration = Duration::from_hours(1);
const CACHE_TTI: Duration = Duration::from_mins(15);
const CACHE_MAX_ACCESSES: u64 = 1000;

/// A [`Provider`] implementation that uses AWS KMS.
///
/// This provider leverages AWS KMS for managing the master key, which is used to protect
/// the Data Encryption Keys (DEKs). The DEKs are generated by AWS KMS and cached in memory
/// to improve throughput and reduce cost.
///
/// ## Architecture
///
/// - Master Key: Managed by AWS KMS, backed by a Hardware Security Module (HSM).
/// - Data Encryption Key (DEK): Generated by AWS KMS. The encrypted form of the DEK is
///   persisted by a `Storage` backend, while the plaintext DEK is cached in memory.
/// - Caching layer for plaintext DEKs to minimize the number of calls to AWS KMS.
pub struct AwsProvider<S> {
    inner: Arc<Inner<S>>,
}

struct Inner<S> {
    client: KmsClient,
    master_id: Arc<OnceCell<String>>,
    master_alias: String,
    dek_id: DekId,
    storage: Arc<S>,
    nonce_gen: NonceGenerator,
    cache: Cache<DekId, (Secret, AeadAlgorithm)>,
    encryption_context: DashMap<String, String>,
}

impl<S: Storage> AwsProvider<S> {
    /// Creates a new `AwsProvider`.
    ///
    /// This initializes the AWS KMS client, sets up the master key alias and DEK ID
    /// based on the hostname, and configures the cache and nonce generator.
    ///
    /// # Arguments
    ///
    /// * `aws_config` - The AWS SDK configuration.
    /// * `hostname` - A hostname of the service using this provider.
    /// * `storage` - A `Storage` implementation for persisting the encrypted DEK.
    pub fn new(aws_config: &SdkConfig, hostname: &str, storage: S) -> Self {
        // Generate deterministic IDs
        let master_alias = format!("alias/kms-{}", MasterId::new(hostname));
        let dek_id = DekId::new(hostname);

        // Initialize AWS SDK
        let kms_client = KmsClient::new(aws_config);

        // Initialize cache
        let cache = Cache::builder()
            .max_capacity(MAX_CACHE_CAPACITY)
            .time_to_live(CACHE_TTL)
            .time_to_idle(CACHE_TTI)
            .max_accesses(CACHE_MAX_ACCESSES)
            .build();

        // Initialize nonce generator
        let mut prefix = [0u8; 4];
        rand::fill(&mut prefix);
        let nonce_gen = NonceGenerator::new().with_prefix(prefix);

        let inner = Inner {
            client: kms_client,
            master_id: Arc::new(OnceCell::new()),
            master_alias,
            dek_id,
            storage: Arc::new(storage),
            nonce_gen,
            cache,
            encryption_context: DashMap::new(),
        };

        Self {
            inner: Arc::new(inner),
        }
    }

    /// Adds a key-value pair to the AWS KMS encryption context.
    ///
    /// The encryption context is a set of non-secret key-value pairs that are passed to AWS KMS
    /// during cryptographic operations. It provides additional authenticated data (AAD) that is
    /// cryptographically bound to the ciphertext.
    ///
    /// This can be used to add context to the encryption, which can then be checked during
    /// decryption to ensure that the data has not been tampered with or used in an unintended
    /// context. It is strongly recommended to set the encryption context.
    pub fn with_encryption_context(self, key: impl Into<String>, value: impl Into<String>) -> Self {
        self.inner
            .encryption_context
            .insert(key.into(), value.into());
        self
    }

    /// Ensures the AWS KMS master key exists.
    async fn try_init_master_key(&self) -> Result<&String> {
        self.inner
            .master_id
            .get_or_try_init(|| async {
                // Try to describe the key by alias
                let inner = &self.inner;
                let op = inner.client.describe_key().key_id(&inner.master_alias);
                let key_id = match op.send().await {
                    Ok(output) => {
                        let key_metadata = output.key_metadata().ok_or_else(|| {
                            Error::Provider(eyre!("No master key metadata in describe response"))
                        })?;
                        key_metadata.key_id().to_string()
                    }
                    Err(SdkError::ServiceError(err)) if err.err().is_not_found_exception() => {
                        // Master key not found, create it
                        let create_result = inner.client.create_key().send().await?;
                        let key_metadata = create_result.key_metadata().ok_or_else(|| {
                            Error::Provider(eyre!("No master key metadata in create response"))
                        })?;
                        let key_id = key_metadata.key_id().to_string();

                        // Create alias — handle concurrent creation race
                        let alias_result = inner
                            .client
                            .create_alias()
                            .alias_name(&inner.master_alias)
                            .target_key_id(&key_id)
                            .send()
                            .await;

                        match alias_result {
                            Ok(_) => key_id,
                            Err(SdkError::ServiceError(err))
                                if err.err().is_already_exists_exception() =>
                            {
                                // Another caller created the alias concurrently.
                                // Re-fetch the actual key ID behind the alias.
                                let output = inner
                                    .client
                                    .describe_key()
                                    .key_id(&inner.master_alias)
                                    .send()
                                    .await?;
                                let key_metadata = output.key_metadata().ok_or_else(|| {
                                    Error::Provider(eyre!(
                                        "No master key metadata in describe response after alias race"
                                    ))
                                })?;
                                key_metadata.key_id().to_string()
                            }
                            Err(err) => return Err(Error::Provider(err.into())),
                        }
                    }
                    Err(err) => return Err(Error::Provider(err.into())),
                };
                Ok(key_id)
            })
            .await
    }

    /// Ensures the DEK exists in storage or generates it via AWS KMS.
    async fn get_or_try_init_dek(&self) -> Result<DataEncryptionKey> {
        let inner = &self.inner;
        // Check storage first
        if let Some(dek) = inner.storage.get_dek(&inner.dek_id).await? {
            return Ok(dek);
        }

        let master_id = self.try_init_master_key().await?;
        let algorithm = AeadAlgorithm(crypto::aead::Algorithm::AesGcm256);
        // Generate DEK via AWS KMS
        let mut request = inner
            .client
            .generate_data_key()
            .key_id(master_id)
            .key_spec(algorithm.try_into()?);

        // Add encryption context if provided
        if !inner.encryption_context.is_empty() {
            let encryption_context: HashMap<String, String> = inner
                .encryption_context
                .iter()
                .map(|entry| (entry.key().clone(), entry.value().clone()))
                .collect();
            request = request.set_encryption_context(Some(encryption_context));
        }
        let output = request.send().await?;

        // Extract plaintext and ciphertext from AWS response
        let plaintext_dek = output
            .plaintext()
            .ok_or_else(|| Error::Provider(eyre!("No plaintext in AWS KMS response")))?
            .as_ref();

        let encrypted_dek = output
            .ciphertext_blob()
            .ok_or_else(|| Error::Provider(eyre!("No ciphertext in AWS KMS response")))?
            .as_ref();

        let dek = DataEncryptionKey::new(
            inner.dek_id.clone(),
            MasterId::from(&*inner.master_alias),
            Some(Secret::from(plaintext_dek)),
            encrypted_dek,
            algorithm,
        );
        inner.storage.upsert_dek(&dek).await?;
        Ok(dek)
    }

    /// Gets the plaintext DEK.
    async fn get_plaintext_dek(&self) -> Result<(Secret, AeadAlgorithm)> {
        let inner = &self.inner;
        // Check cache first
        if let Some(cached) = inner.cache.get(&inner.dek_id).await {
            return Ok(cached);
        }
        // Get DEK either from storage or generate it
        let dek = self.get_or_try_init_dek().await?;
        let alg = dek.algorithm;

        // If we have a plaintext key, return it
        if let Some(plaintext) = dek.plaintext_key {
            inner
                .cache
                .insert(inner.dek_id.clone(), (plaintext.clone(), alg))
                .await;
            return Ok((plaintext, alg));
        }

        // Decrypt DEK via AWS KMS
        let mut request = inner
            .client
            .decrypt()
            .ciphertext_blob(Blob::new(&*dek.encrypted_key));

        // Add encryption context if provided
        if !inner.encryption_context.is_empty() {
            let encryption_context: HashMap<String, String> = inner
                .encryption_context
                .iter()
                .map(|entry| (entry.key().clone(), entry.value().clone()))
                .collect();
            request = request.set_encryption_context(Some(encryption_context));
        }
        let output = request.send().await?;

        // Extract and decode plaintext
        let plaintext_dek = output
            .plaintext()
            .ok_or_else(|| Error::Provider(eyre!("No plaintext in AWS KMS response")))?
            .as_ref();

        let secret = Secret::from(plaintext_dek);
        // Cache the plaintext DEK
        inner
            .cache
            .insert(inner.dek_id.clone(), (secret.clone(), alg))
            .await;
        Ok((secret, alg))
    }
}

#[async_trait::async_trait]
impl<S: Storage> Provider for AwsProvider<S> {
    async fn encrypt<T>(&self, aad: &[u8], plain_inout: &mut T) -> crate::Result<()>
    where
        T: AsMut<[u8]> + for<'a> Extend<&'a u8> + Send,
    {
        // Get DEK
        let (dek, alg) = self.get_plaintext_dek().await?;

        // Encrypt data with DEK
        let key = AesKey::new(alg.into(), dek.expose())?;
        let nonce = self.inner.nonce_gen.next()?;
        key.encrypt_append_tag(&nonce, aad, plain_inout)?;
        // Append nonce to the end of the buffer
        plain_inout.extend(nonce.iter());
        Ok(())
    }

    async fn decrypt<'a>(&self, aad: &[u8], cipher_inout: &'a mut [u8]) -> Result<&'a [u8]> {
        // Validate input format: ciphertext || tag || nonce
        if cipher_inout.len() < NONCE_LENGTH + TAG_LENGTH {
            return Err(Error::Crypto(eyre!("Invalid ciphertext blob")));
        }

        let nonce_start = cipher_inout.len() - NONCE_LENGTH;
        // Safety: We know the length is correct from the calculation above
        let nonce: [u8; NONCE_LENGTH] = cipher_inout[nonce_start..].try_into().unwrap();

        // Get DEK
        let (dek, alg) = self.get_plaintext_dek().await?;

        // Decrypt data with DEK
        let key = AesKey::new(alg.into(), dek.expose())?;
        let encrypted_slice = &mut cipher_inout[..nonce_start];
        let plaintext_dek = key.decrypt(&nonce, aad, encrypted_slice)?;
        Ok(plaintext_dek)
    }
}

impl<S: Storage> Clone for AwsProvider<S> {
    fn clone(&self) -> Self {
        Self {
            inner: self.inner.clone(),
        }
    }
}

impl<S: Storage> fmt::Debug for AwsProvider<S> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("AwsProvider")
            .field("master_id", &self.inner.master_id)
            .field("master_alias", &self.inner.master_alias)
            .field("dek_id", &self.inner.dek_id)
            .field("nonce_gen", &self.inner.nonce_gen)
            .field("cache_entry_count", &self.inner.cache.entry_count())
            .field("encryption_context", &self.inner.encryption_context)
            .finish()
    }
}

impl TryFrom<AeadAlgorithm> for DataKeySpec {
    type Error = Error;

    fn try_from(algorithm: AeadAlgorithm) -> std::result::Result<Self, Self::Error> {
        use crypto::aead::Algorithm;
        let alg: Algorithm = algorithm.into();
        match alg {
            Algorithm::AesGcm128 => Ok(DataKeySpec::Aes128),
            Algorithm::AesGcm256 => Ok(DataKeySpec::Aes256),
            _ => Err(Error::Provider(eyre!("{alg} is not supported by AWS KMS"))),
        }
    }
}

impl<E> From<SdkError<E>> for Error
where
    E: std::error::Error + Send + Sync + 'static,
{
    fn from(error: SdkError<E>) -> Self {
        Error::Provider(eyre!("AWS KMS reported an error: {error}"))
    }
}
